created PULL_REQUEST_TEMPLATE.md
hhu-propra1/time-tracker pull request #32
Opened 2022-05-26 10:00 UTC by dragonempire96

created PULL_REQUEST_TEMPLATE.md for the issue #27

2022-05-26 10:04 UTC, n2o commented
Hm das ist sehr ausführlich. Können wir das reduzieren? Einiges ist unnötig, da die Github Actions ja bspw. alle Tests und Checkstyle ausführen. Vielleicht reichen diese Punkte:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

Folgende Sektionen finde ich persönlich uninteressant, aber da kannst du gerne auch deine Meinung zu äußern:
* Motivation and Context
* How Has This Been Tested?
* Screenshots (if appropriate):
* Types of changes
Die können von mir aus alle weg. Liest eh keiner :D

Wichtig finde ich eine Verlinkung auf den Issue. Also am liebsten so klein eindampfen wie es geht :-)

2022-05-26 10:04 UTC, n2o requested changes
Hm das ist sehr ausführlich. Können wir das reduzieren? Einiges ist unnötig, da die Github Actions ja bspw. alle Tests und Checkstyle ausführen. Vielleicht reichen diese Punkte:

 My code follows the code style of this project.
 My change requires a change to the documentation.
 I have updated the documentation accordingly.
 I have read the CONTRIBUTING document.
 I have added tests to cover my changes.
Folgende Sektionen finde ich persönlich uninteressant, aber da kannst du gerne auch deine Meinung zu äußern:

Motivation and Context
How Has This Been Tested?
Screenshots (if appropriate):
Types of changes
Die können von mir aus alle weg. Liest eh keiner :D
Wichtig finde ich eine Verlinkung auf den Issue. Also am liebsten so klein eindampfen wie es geht :-)

2022-05-26 10:12 UTC, dragonempire96 commented
Klar können wir das kürzen

2022-05-26 10:16 UTC, dragonempire96 commented
Und Screenshots würde ich lassen, falls was implementiert wird was eine Grafik ausgibt. Damit man die Ausgabe sieht ohne einmal das Programm ausführen zu müssen.

2022-05-26 10:17 UTC, n2o commented
Ok

2022-05-27 08:29 UTC, n2o approved these changes

2022-05-27 08:29 UTC, merged