Add/tracking
hhu-propra1/time-tracker pull request #38
Opened 2022-06-10 19:21 UTC by dragonempire96

## Description

Ich habe die Funktion für ein automatisches Tracken der Zeit hinzugefügt

## Related Issue

Issue #37 

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

2022-06-11 11:43 UTC, xor50 commented on src/test/java/de/propra/timetracker/TempFileTest.java
> +        String project = "Propar1";
typo

2022-06-20 08:53 UTC, dragonempire96 commented
ist das nun eigentlich gut so?

2022-06-20 13:33 UTC, n2o requested changes

2022-06-20 13:33 UTC, n2o commented on src/main/java/de/propra/timetracker/TimeTrackerCLI.java
> +        options.addOption(trackStop);
Hier bitte genauer reinschreiben wie die Verwendung ist. In der README ist das gut gelöst, aber wenn man nun `--help` auf der Konsole aufruft, ergibt es nicht so viel Sinn und man weiß nicht was man da noch schreiben muss. 

Das sollten wir perspektivisch auch noch bei den anderen Punkten ergänzen. Die Hilfe soll ja erklären wie ich nun die Parameter da eingebe etc. :-) Die README ist ja eher was für Devs.

2022-06-20 13:34 UTC, n2o commented
Sorry, hatte das nicht so aufm Schirm. Die README noch anpassen, dann passt das 👍

2022-06-20 15:16 UTC, dragonempire96 commented
![image](https://user-images.githubusercontent.com/82451801/174632845-98614b26-7526-441c-8d39-8f957d019efc.png)
![image](https://user-images.githubusercontent.com/82451801/174632945-f01466ea-260f-40ff-858a-e7ad7763cf55.png)

2022-06-20 19:37 UTC, merged