Create README.md
hhu-propra1/time-tracker pull request #5
Opened 2022-05-19 21:23 UTC by sakla106

Fügt eine README nach Anforderungen von Issue #2 hinzu

2022-05-19 22:41 UTC, n2o requested changes
Super! Bitte die Syntax noch ein wenig anpassen :-)

2022-05-19 22:41 UTC, n2o commented on README.md
> + # Why does the time-tracker exist?
```suggestion
## Why does the time-tracker exist?
```

Unterüberschriften werden mit einer weiteren führenden Raute markiert. Bspw.

# Heading 1 (die Haupt-Headline -- davon sollte es nur eine geben
## Heading 2 (ordnet sich der H1 unter
### Heading 3
#### Heading 4
...

Bitte entsprechend anpassen :-)

2022-05-19 22:41 UTC, n2o commented on README.md
> + First you have to create a shadow jar with the imported gradle plugin via tasks > shadow > shadowJar.
Bitte unnötige Einrückung entfernen.

2022-05-20 06:12 UTC, sakla106 commented on README.md
> + First you have to create a shadow jar with the imported gradle plugin via tasks > shadow > shadowJar.
Heyho, was genau meinst du mit unnötiger Einrückung? Die Leerzeilen zwischen Text und Überschriften? Oder soll aus "tasks > shadow > shadowJar" eher "tasks>shadow>shadowJar" werden? Stehe ein bisschen auf dem Schlauch :D

2022-05-20 07:33 UTC, n2o approved these changes

2022-05-20 07:33 UTC, n2o approved these changes

2022-05-20 07:33 UTC, merged